

name: publish
on:
  push:
    branches:
      - main
      - adopt-argo-and-gh
jobs:
    # runs-on: [self-hosted]
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Argo Workflow Submit
        uses: ./.github/actions/argo-submit
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SESSION_NAME: ${{ secrets.AWS_SESSION_NAME }}
          ARGO_SERVER_URL: ${{ secrets.ARGO_SERVER_URL }}
        with:
          workflow_yaml_path: ".argo/publish/builder.yaml"
          parameter_file_path: ".argo/publish/params.yaml"
        # todo look into outputs
