

name: local
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - adopt-argo-and-gh
#! call out repository_dispatch: this would be on last commit to default branch?
  workflow_dispatch:
    # inputs:
    #   name:
    #     description: 'Person to greet'
    #     required: true
    #     default: 'Mona the Octocat'
    #   home:
    #     description: 'location'
    #     required: false
    #     default: 'The Octoverse'


jobs:
    # runs-on: [self-hosted]
  hello_world_job:
    runs-on: ubuntu-latest
    name: argo submit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Argo Workflow Submit
        uses: ./.github/actions/argo-submit
        env: # todo are these needed
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SESSION_NAME: ${{ secrets.AWS_SESSION_NAME }}
          ARGO_SERVER_URL: ${{ secrets.ARGO_SERVER_URL }}
        with:
          workflow_yaml_path: ".argo/publish/main.yaml"
          parameter_file_path: ".argo/publish/params.yaml"
        # todo look into outputs
